- name: Play 1 - Run Roles for miscellaneous softwares,Apache & Tomcat
  hosts: webservers
  become: yes
  vars:
    v_role_path: "roles"
  roles:
    - "{{ v_role_path }}/miscellaneous"
    - "{{ v_role_path }}/apache"
    - "{{ v_role_path }}/tomcat"


- name: Play 5 - Start Tomcat Servers
  hosts: webservers
  become: yes
  become_user: root
  tasks:
    - name: start tomcat
      command: nohup sh /etc/tomcat/bin/startup.sh
      tags: start-tomcat
